name: Realm Dart CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-android:
    name: Build Android
    uses: ./.github/workflows/build-native.yml
    with:
     runner: ubuntu-20.04
     binary: android
     build: '["android-x86", "android-x86_64", "android-armeabi-v7a", "android-arm64-v8a"]'

  build-android-combined:
    name: Android binaries combine
    needs: build-android
    uses: ./.github/workflows/binary-combine-android.yml

# Generator jobs

  generator:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest
    name: Generator Tests
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          submodules: 'recursive'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Delete generated files
        run: find . -name "*.g.dart" -not -path "./generator/*" -delete
        shell: bash

      - name: Run generator in realm-dart repo
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Run generator in realm-dart/example
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs
        working-directory: ./example/

      - name: Run generator in realm_flutter/example
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs
        working-directory: ./flutter/realm_flutter/example/

      - name: Install LLVM
        run: sudo apt update && sudo apt-get install -y libclang-dev
        if: ${{ matrix.os == 'ubuntu' }}

      - name: Run ffigen
        run: dart run ffigen --config config.yaml
        working-directory: ./ffigen

      - name: Validate there are no uncommitted changes
        run: |
          changedFiles=$(git --no-pager diff -w)
          if [ "$changedFiles" ]; then
            git --no-pager diff -w
            exit 1
          fi
        shell: bash

      - name: Run generator tests
        run: |
          dart pub get
          dart test -r expanded --coverage ./coverage/ --test-randomize-ordering-seed random
        working-directory: ./generator/

      - name: Generate generator coverage report
        if: matrix.os == 'ubuntu'
        run: |
          dart run coverage:format_coverage \
            --in coverage/ \
            --out ./coverage/lcov.info \
            --check-ignore \
            --lcov \
            --packages .dart_tool/package_config.json \
            --report-on lib
        working-directory: ./generator/

      - name: Publish Generator Coverage
        if: matrix.os == 'ubuntu'
        id: publish-coverage
        uses: coverallsapp/github-action@f350da2c033043742f89e8c0b7b5145a1616da6d
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: generator
          path-to-lcov: ./generator/coverage/lcov.info
          parallel: true

      - name: Output Coveralls response
        if: matrix.os == 'ubuntu'
        run: echo ${{ steps.publish-coverage.outputs.coveralls-api-result }}
